- name: Install Java
  yum:
    name: "java-1.8.0-openjdk"
    state: latest
    disablerepo: "epel,google-cloud-compute"
- name: Install PIP
  yum:
    name: "pip3"
    state: latest  
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
